name: webrtc_test
description: Flutter Video Calling using WebRTC and Firebase.

publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

# ------------------------------
dependencies:
  flutter:
    sdk: flutter
  
  # device systems
  provider: ^4.3.2+2
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+11
  path_provider: ^1.6.18
  fluttertoast: ^7.1.1
  wakelock: ^0.2.0+1
  device_info: ^0.4.2+9

  # utility
  hive: ^1.4.4+1
  email_validator: ^1.0.5
  cached_network_image: ^2.3.2+1
  emoji_picker: ^0.1.0
  intl: ^0.16.1
  assets_audio_player: ^2.0.13
  
  # cloud comms
  agora_rtc_engine: ^3.1.2
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.1.0
  firebase_messaging: ^8.0.0-dev.9
  flutter_ios_voip_kit: ^0.0.5


# ------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

# ------------------------------
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/applogo3.png"
  # flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
